# Numpy

```
NumPy (short for Numerical Python) is a powerful open-source Python library used for numerical and scientific computing.

 Key Features of NumPy:

- Multidimensional arrays: The core of NumPy is the ndarray, a fast, memory-efficient array for storing and manipulating data.

- Vectorized operations: Perform element-wise operations on arrays without writing loops.

- Mathematical functions: Includes a wide range of mathematical operations like linear algebra, statistics, and more.

- Broadcasting: Efficiently performs arithmetic operations on arrays of different shapes.

- Integration: Works well with other scientific libraries like Pandas, Matplotlib, and SciPy.
```

### `creating an numpy array`

In [8]:
# first we need to import numpy 
import numpy as np # np is the short form, you can np instead of numpy

In [7]:
# creating 1D array using np.array 
# arrays works on homogeneous data only
arr = np.array([1,2,3,4,5]) # 1D array also called vector
print(arr)
print(type(arr)) 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# 2D array also matrices
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2D means collection of 1D's 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# 3D array also called tensors 
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])# 3D means collection of 2D values
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [11]:
# creating a 1D array using arange function 
arr = np.arange(0,21,2) # (start_index:end_index:step_size)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
# creating matrix of ones 
arr = np.ones((3,5)) # we need to give the parameters in tuple, in tuple(no_of_rows,no_of_cols)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [16]:
# creating matrix of zeros 
arr = np.zeros((3,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
# reshape the array from one Dimension to another 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
reshaped_arr = np.reshape(arr,9) # here converting the all values 
print(reshaped_arr) 
reshaped_arr = np.reshape(arr,(3,3))
print(reshaped_arr)
# note : the product of the tuple should be equal to the number of values otherwise error
arr = np.arange(1,13).reshape((2,2,3)) # it will create 2 2X3 matrices
arr

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
# identity matrix 
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# linspace : linear space uniformly distribute the values from starting value to ending value
arr = np.linspace(1,10,10,dtype = int,axis=0)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
# random values between 0 to 1
arr = np.random.random(10) # 10 random values
arr

array([0.26629082, 0.60730683, 0.25981916, 0.73468253, 0.78289245,
       0.63209278, 0.27969646, 0.78043478, 0.58957717, 0.08084825])

In [ ]:
# dtype : you can change the datatype of any array

In [45]:
arr = np.array([1,2,3,4,5]) # by default int
arr

array([1, 2, 3, 4, 5])

In [46]:
arr = np.array([1,2,3,4,5],dtype=float)
arr

array([1., 2., 3., 4., 5.])

In [48]:
arr = np.array([1,2,3,4,5],dtype=bool) # return 1 for non zero values
arr

array([ True,  True,  True,  True,  True])

In [49]:
arr = np.array([1,2,3,4,5],dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

### `Array Attributes`

In [66]:
# lets create some exmaples of arrays 
a1 = np.array([1,2,3,4,5],dtype=np.int32)
a2 = np.arange(1,11,dtype=float).reshape((5,2))
a3 = np.arange(8,dtype=np.int64).reshape((2,2,2))

In [55]:
a1

array([1, 2, 3, 4, 5])

In [56]:
a2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [57]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
# ndim : defines array dimension 
print(a1.ndim)
print(a2.ndim) 
print(a3.ndim)

1
2
3


In [61]:
# shape : defines the number of rows and columns 
print(a1.shape)
print(a2.shape) 
print(a3.shape) 

(5,)
(5, 2)
(2, 2, 2)


In [69]:
# size : returns number of elements in an array 
print(a1.size) 
print(a2.size) 
print(a3.size) 

5
10
8


In [68]:
# dtype : returns the datatype of an array 
print(a1.dtype) 
print(a2.dtype) 
print(a3.dtype)

int32
float64
int64


In [71]:
# itemsize : returns the number of bytes taken by each element, this is based on datatype 
print(a1.itemsize) 
print(a2.itemsize) 
print(a3.itemsize) # int64 and float64 has same bytes (8)

4
8
8


### `changing datatype`

In [72]:
# astype() function 
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [75]:
a3.astype("int16")

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

In [76]:
a3.astype("complex")

array([[[0.+0.j, 1.+0.j],
        [2.+0.j, 3.+0.j]],

       [[4.+0.j, 5.+0.j],
        [6.+0.j, 7.+0.j]]])

### `array operations`
``` 
scalar operations 
vector operations 
```

In [ ]:
# scalar operations : performing operations on array with single element (scalar)
# again two types 1) arithmetic 2) relational

In [81]:
# arithmetic operations (all operators)
a1 = np.arange(1,11)
print(a1)
print(a1+10) # added 10 to each element in an array
print(a1*5)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[ 5 10 15 20 25 30 35 40 45 50]


In [82]:
# relational (all operators) 
a1 > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [83]:
a1 == 5

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
# # vector operations : performing operations on array with another array (vector)
# only  1) arithmetic

In [86]:
# artihmetic 
a1 = np.arange(1,11) 
a2 = np.arange(11,21)
print(a1)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [87]:
a1 + a2 # each from both arrays are added 


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [88]:
a1 * a2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [89]:
# note : number of values should be same in both arrays

In [90]:
# example 
a1 = np.arange(1,11) 
a2 = np.arange(11,20)
print(a1)
print(a2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]


In [91]:
a1 + a2

ValueError: operands could not be broadcast together with shapes (10,) (9,) 