# numpy Important functions

In [2]:
import numpy as np

In [3]:
a = np.random.randint(1,100,15)
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [4]:
b = np.random.randint(1,100,15).reshape(5,3)
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

### np.sort

In [5]:
# sorts the data 

In [6]:
np.sort(a)

array([12, 31, 37, 46, 51, 52, 53, 57, 58, 65, 65, 71, 85, 96, 98])

In [7]:
np.sort(a)[::-1]

array([98, 96, 85, 71, 65, 65, 58, 57, 53, 52, 51, 46, 37, 31, 12])

In [8]:
np.sort(b) # row wise by default

array([[35, 91, 96],
       [13, 40, 74],
       [43, 85, 90],
       [53, 76, 86],
       [ 1,  7, 53]])

In [9]:
np.sort(b,axis=0) # column wise

array([[ 1,  7, 53],
       [13, 40, 74],
       [35, 76, 85],
       [43, 90, 86],
       [53, 91, 96]])

### np.append

In [10]:
# it appends the element at the last 

In [11]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [12]:
np.append(a,100)

array([ 51,  65,  85,  37,  71,  57,  46,  98,  58,  12,  53,  96,  65,
        52,  31, 100])

In [13]:
np.append(a,[1,2,3,4])

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31,  1,  2,
        3,  4])

In [14]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [15]:
np.append(b,np.ones((1,3)),axis=0)

array([[35., 91., 96.],
       [13., 40., 74.],
       [43., 90., 85.],
       [53., 76., 86.],
       [ 1.,  7., 53.],
       [ 1.,  1.,  1.]])

In [16]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[35., 91., 96.,  1.],
       [13., 40., 74.,  1.],
       [43., 90., 85.,  1.],
       [53., 76., 86.,  1.],
       [ 1.,  7., 53.,  1.]])

### np.where

In [17]:
# np where returns the indicies of array based on condition

In [18]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [19]:
np.where(a>50)

(array([ 0,  1,  2,  4,  5,  7,  8, 10, 11, 12, 13], dtype=int64),)

In [20]:
# you can replace the values based on condtion np.where(condition,code if true,code if false)
np.where(a>50,1,0)

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0])

In [21]:
np.where(b>50,1,0)

array([[0, 1, 1],
       [0, 0, 1],
       [0, 1, 1],
       [1, 1, 1],
       [0, 0, 1]])

In [22]:
np.where(a%2==0,0,a)

array([51, 65, 85, 37, 71, 57,  0,  0,  0,  0, 53,  0, 65,  0, 31])

### np.unique

In [23]:
# it returns  unique values of an array

In [24]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [25]:
np.unique(a)

array([12, 31, 37, 46, 51, 52, 53, 57, 58, 65, 71, 85, 96, 98])

In [26]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [27]:
np.unique(b)

array([ 1,  7, 13, 35, 40, 43, 53, 74, 76, 85, 86, 90, 91, 96])

### np.expnad_ndims

In [28]:
# it make the 1D to 2D if already 2D it makes 3D and so on 
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [29]:
a.shape

(15,)

In [30]:
np.expand_dims(a,axis=0)

array([[51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31]])

In [31]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [32]:
np.expand_dims(a,axis=1)

array([[51],
       [65],
       [85],
       [37],
       [71],
       [57],
       [46],
       [98],
       [58],
       [12],
       [53],
       [96],
       [65],
       [52],
       [31]])

In [33]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.argmax

In [34]:
# it return the index of max value column or row wise 

In [35]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [36]:
np.argmax(a) # 98 is the max and its index is 9

7

In [37]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [38]:
np.argmax(b,axis=0) # column wise

array([3, 0, 0], dtype=int64)

In [39]:
np.argmax(b,axis=1) # row wise

array([2, 2, 1, 2, 2], dtype=int64)

# no.argmin

In [40]:
# it return the index of min value column or row wise 

In [41]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [42]:
np.argmin(a)

9

In [43]:
a[np.argmax(a)]

98

In [44]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [45]:
np.argmin(b,axis=0)

array([4, 4, 4], dtype=int64)

In [46]:
np.argmin(b,axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

# np.cumsum

In [47]:
# it return the cummulative sum of an array

In [48]:
a 

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [56]:
np.cumsum(a) # [51, 51+65, 51+65+81, .........]

array([ 51, 116, 201, 238, 309, 366, 412, 510, 568, 580, 633, 729, 794,
       846, 877])

In [50]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [51]:
np.cumsum(b)

array([ 35, 126, 222, 235, 275, 349, 392, 482, 567, 620, 696, 782, 783,
       790, 843])

In [52]:
np.cumsum(b,axis=0)

array([[ 35,  91,  96],
       [ 48, 131, 170],
       [ 91, 221, 255],
       [144, 297, 341],
       [145, 304, 394]])

In [53]:
np.cumsum(b,axis=1)

array([[ 35, 126, 222],
       [ 13,  53, 127],
       [ 43, 133, 218],
       [ 53, 129, 215],
       [  1,   8,  61]])

# np.cumprod

In [54]:
a

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [55]:
np.cumprod(a) # [51, 51*65, 51*65*85 ,........]

array([         51,        3315,      281775,    10425675,   740222925,
        -756966235,  -460708442,  2095212940,  1263266232, -2020674400,
         278439200,   960359424, -2001146880,  -980422656,  -328331264])

In [57]:
b

array([[35, 91, 96],
       [13, 40, 74],
       [43, 90, 85],
       [53, 76, 86],
       [ 1,  7, 53]])

In [58]:
np.cumprod(b,axis=0) # cloumn wise

array([[         35,          91,          96],
       [        455,        3640,        7104],
       [      19565,      327600,      603840],
       [    1036945,    24897600,    51930240],
       [    1036945,   174283200, -1542664576]])

In [59]:
np.cumprod(b,axis=1) # row wise

array([[    35,   3185, 305760],
       [    13,    520,  38480],
       [    43,   3870, 328950],
       [    53,   4028, 346408],
       [     1,      7,    371]])

# np.percentile

In [ ]:
#  a statistical measure used to determine the value below which a given percentage of observations in a dataset falls

In [60]:
a 

array([51, 65, 85, 37, 71, 57, 46, 98, 58, 12, 53, 96, 65, 52, 31])

In [61]:
np.percentile(a,50) # internally it is sorted

57.0

In [62]:
np.median(a)

57.0

# np.corrcoef

In [63]:
"""
it drescribe how the strengh of the relationship between variables
it returns the value between -1 to 1 i means to variables are strongly postive related,
-1 means strongly negative related , 
0 means no relationship between them
"""

In [65]:
a = np.arange(1,100,10)                #    a , b
b = np.arange(1,100,10)              # a    1   1
np.corrcoef(a,b)                     # b    1   1

array([[1., 1.],
       [1., 1.]])

In [66]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)   
np.corrcoef(a,b)

array([[1.        , 0.06741371],
       [0.06741371, 1.        ]])

# np.histogram

```
The numpy.histogram() function is a core tool for statistical analysis in NumPy, used to compute the frequency distribution of numerical data by grouping values into bins
```

In [67]:
a 

array([78, 61, 15, 86, 17, 96, 42, 57, 32, 57])

In [68]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 0, 1, 1, 2, 1, 1, 1, 1], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [69]:
# in the output 
# 0-10 : 0 values ,10-20 : 2 values ,20-30 : 0 values ,.......

# np.isin

In [ ]:
# it is used to check whether the array elements are present in existing array

In [70]:
a

array([78, 61, 15, 86, 17, 96, 42, 57, 32, 57])

In [74]:
items = [10,20,40,30,96,100] # you can check single item also


In [75]:
np.isin(a,items) # SYNTAX : isin("exisitng array","new array")

array([False, False, False, False, False,  True, False, False, False,
       False])

In [76]:
a[np.isin(a,items)]

array([96])

In [77]:
np.isin(a,57)

array([False, False, False, False, False, False, False,  True, False,
        True])

In [78]:
a[np.isin(a,57)]

array([57, 57])

# np.flip

In [ ]:
# is used to reverse the array values  

In [79]:
a

array([78, 61, 15, 86, 17, 96, 42, 57, 32, 57])

In [80]:
np.flip(a) 

array([57, 32, 57, 42, 96, 17, 86, 15, 61, 78])

In [86]:
b = b.reshape(5,2)

In [87]:
b

array([[28, 98],
       [39, 58],
       [54, 45],
       [59,  4],
       [22, 26]])

In [89]:
np.flip(b)

array([[26, 22],
       [ 4, 59],
       [45, 54],
       [58, 39],
       [98, 28]])

In [90]:
np.flip(b,axis=0) # column wise

array([[22, 26],
       [59,  4],
       [54, 45],
       [39, 58],
       [28, 98]])

In [92]:
np.flip(b,axis=1) # row wise

array([[98, 28],
       [58, 39],
       [45, 54],
       [ 4, 59],
       [26, 22]])

# np.put

In [ ]:
# is used to replace the values  but you need to give the index values

In [93]:
a

array([78, 61, 15, 86, 17, 96, 42, 57, 32, 57])

In [99]:
np.put(a,[0,1,7,9],[100,200,300,300])

In [100]:
a

array([100, 200,  15,  86,  17,  96,  42, 300,  32, 300])

# np.delete

In [101]:
# is used the delete the elements based on index 

In [102]:
a

array([100, 200,  15,  86,  17,  96,  42, 300,  32, 300])

In [105]:
np.delete(a,[0,1])

array([ 15,  86,  17,  96,  42, 300,  32, 300])

In [106]:
np.delete(a,[0,1,7,9])

array([15, 86, 17, 96, 42, 32])

# set functions

In [ ]:
# np.union1d 
# np.intersect1d
# np.setdiff1d
# np.setxor1d
# np.in1d

In [107]:
m = np.array([1,2,3,4,5,6])
n = np.array([5,6,7,8,9,10])

In [108]:
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
np.intersect1d(m,n)

array([5, 6])

In [110]:
np.setdiff1d(m,n)

array([1, 2, 3, 4])

In [111]:
np.setdiff1d(n,m)

array([ 7,  8,  9, 10])

In [113]:
np.in1d(m,1)

array([ True, False, False, False, False, False])

In [115]:
m[np.in1d(m,1)]

array([1])

# clip function 

In [ ]:
# it is used to set the limit to an array if value values below the range it replaced by min range value , 
# or if values are above max limit value those can be eplaced by max value

In [116]:
a = np.random.randint(1,100,25)

In [118]:
a

array([84, 37, 64, 87,  7, 53, 36, 14,  1, 19, 21, 49, 43, 67, 37, 73, 84,
       88, 12, 83, 18, 76, 30, 66, 87])

In [117]:
np.clip(a,a_min=25,a_max=80)

array([80, 37, 64, 80, 25, 53, 36, 25, 25, 25, 25, 49, 43, 67, 37, 73, 80,
       80, 25, 80, 25, 76, 30, 66, 80])